#!/bin/sh

ldflags=$(python2.7-config --ldflags)
#echo "$ldflags"
#gcc call_function.c -o call_function -lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic
gcc call_function.c -o call_function $ldflags

exit 0
